## Importing Libraries


In [65]:
import numpy as np 
import pandas as pd

## Importing Dataset

In [66]:
AUS=pd.read_csv(r"C:\Users\Kwame Eben\Downloads\machine\weatherAUS.csv")

In [67]:
AUS

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0       2008-12-01   Albury     13.4     22.9       0.6          NaN   
1       2008-12-02   Albury      7.4     25.1       0.0          NaN   
2       2008-12-03   Albury     12.9     25.7       0.0          NaN   
3       2008-12-04   Albury      9.2     28.0       0.0          NaN   
4       2008-12-05   Albury     17.5     32.3       1.0          NaN   
...            ...      ...      ...      ...       ...          ...   
145455  2017-06-21    Uluru      2.8     23.4       0.0          NaN   
145456  2017-06-22    Uluru      3.6     25.3       0.0          NaN   
145457  2017-06-23    Uluru      5.4     26.9       0.0          NaN   
145458  2017-06-24    Uluru      7.8     27.0       0.0          NaN   
145459  2017-06-25    Uluru     14.9      NaN       0.0          NaN   

        Sunshine WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  \
0            NaN           W           44.0          W  ...        71.0   
1            NaN         WNW           44.0        NNW  ...        44.0   
2            NaN         WSW           46.0          W  ...        38.0   
3            NaN          NE           24.0         SE  ...        45.0   
4            NaN           W           41.0        ENE  ...        82.0   
...          ...         ...            ...        ...  ...         ...   
145455       NaN           E           31.0         SE  ...        51.0   
145456       NaN         NNW           22.0         SE  ...        56.0   
145457       NaN           N           37.0         SE  ...        53.0   
145458       NaN          SE           28.0        SSE  ...        51.0   
145459       NaN         NaN            NaN        ESE  ...        62.0   

        Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0              22.0       1007.7       1007.1       8.0       NaN     16.9   
1              25.0       1010.6       1007.8       NaN       NaN     17.2   
2              30.0       1007.6       1008.7       NaN       2.0     21.0   
3              16.0       1017.6       1012.8       NaN       NaN     18.1   
4              33.0       1010.8       1006.0       7.0       8.0     17.8   
...             ...          ...          ...       ...       ...      ...   
145455         24.0       1024.6       1020.3       NaN       NaN     10.1   
145456         21.0       1023.5       1019.1       NaN       NaN     10.9   
145457         24.0       1021.0       1016.8       NaN       NaN     12.5   
145458         24.0       1019.4       1016.5       3.0       2.0     15.1   
145459         36.0       1020.2       1017.9       8.0       8.0     15.0   

        Temp3pm  RainToday  RainTomorrow  
0          21.8         No            No  
1          24.3         No            No  
2          23.2         No            No  
3          26.5         No            No  
4          29.7         No            No  
...         ...        ...           ...  
145455     22.4         No            No  
145456     24.5         No            No  
145457     26.1         No            No  
145458     26.0         No            No  
145459     20.9         No           NaN  

[145460 rows x 23 columns]

## Exploring Dataset

In [68]:
AUS.head

<bound method NDFrame.head of               Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0       2008-12-01   Albury     13.4     22.9       0.6          NaN   
1       2008-12-02   Albury      7.4     25.1       0.0          NaN   
2       2008-12-03   Albury     12.9     25.7       0.0          NaN   
3       2008-12-04   Albury      9.2     28.0       0.0          NaN   
4       2008-12-05   Albury     17.5     32.3       1.0          NaN   
...            ...      ...      ...      ...       ...          ...   
145455  2017-06-21    Uluru      2.8     23.4       0.0          NaN   
145456  2017-06-22    Uluru      3.6     25.3       0.0          NaN   
145457  2017-06-23    Uluru      5.4     26.9       0.0          NaN   
145458  2017-06-24    Uluru      7.8     27.0       0.0          NaN   
145459  2017-06-25    Uluru     14.9      NaN       0.0          NaN   

        Sunshine WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  \
0            NaN           W  

In [69]:
AUS.describe

<bound method NDFrame.describe of               Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0       2008-12-01   Albury     13.4     22.9       0.6          NaN   
1       2008-12-02   Albury      7.4     25.1       0.0          NaN   
2       2008-12-03   Albury     12.9     25.7       0.0          NaN   
3       2008-12-04   Albury      9.2     28.0       0.0          NaN   
4       2008-12-05   Albury     17.5     32.3       1.0          NaN   
...            ...      ...      ...      ...       ...          ...   
145455  2017-06-21    Uluru      2.8     23.4       0.0          NaN   
145456  2017-06-22    Uluru      3.6     25.3       0.0          NaN   
145457  2017-06-23    Uluru      5.4     26.9       0.0          NaN   
145458  2017-06-24    Uluru      7.8     27.0       0.0          NaN   
145459  2017-06-25    Uluru     14.9      NaN       0.0          NaN   

        Sunshine WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  \
0            NaN          

## Encoding dataset

In [70]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
AUS['Location']=le.fit_transform(AUS.Location.values)
AUS['WindGustDir']=le.fit_transform(AUS.WindGustDir.values)
AUS['WindDir9am']=le.fit_transform(AUS.WindDir9am.values)
AUS['WindDir3pm']=le.fit_transform(AUS.WindDir3pm.values)
AUS['RainToday']= le.fit_transform(AUS.RainToday.values)
AUS['RainTomorrow']=le.fit_transform(AUS.RainTomorrow.values)


In [71]:
AUS

Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0       2008-12-01         2     13.4     22.9       0.6          NaN   
1       2008-12-02         2      7.4     25.1       0.0          NaN   
2       2008-12-03         2     12.9     25.7       0.0          NaN   
3       2008-12-04         2      9.2     28.0       0.0          NaN   
4       2008-12-05         2     17.5     32.3       1.0          NaN   
...            ...       ...      ...      ...       ...          ...   
145455  2017-06-21        41      2.8     23.4       0.0          NaN   
145456  2017-06-22        41      3.6     25.3       0.0          NaN   
145457  2017-06-23        41      5.4     26.9       0.0          NaN   
145458  2017-06-24        41      7.8     27.0       0.0          NaN   
145459  2017-06-25        41     14.9      NaN       0.0          NaN   

        Sunshine  WindGustDir  WindGustSpeed  WindDir9am  ...  Humidity9am  \
0            NaN           13           44.0          13  ...         71.0   
1            NaN           14           44.0           6  ...         44.0   
2            NaN           15           46.0          13  ...         38.0   
3            NaN            4           24.0           9  ...         45.0   
4            NaN           13           41.0           1  ...         82.0   
...          ...          ...            ...         ...  ...          ...   
145455       NaN            0           31.0           9  ...         51.0   
145456       NaN            6           22.0           9  ...         56.0   
145457       NaN            3           37.0           9  ...         53.0   
145458       NaN            9           28.0          10  ...         51.0   
145459       NaN           16            NaN           2  ...         62.0   

        Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0              22.0       1007.7       1007.1       8.0       NaN     16.9   
1              25.0       1010.6       1007.8       NaN       NaN     17.2   
2              30.0       1007.6       1008.7       NaN       2.0     21.0   
3              16.0       1017.6       1012.8       NaN       NaN     18.1   
4              33.0       1010.8       1006.0       7.0       8.0     17.8   
...             ...          ...          ...       ...       ...      ...   
145455         24.0       1024.6       1020.3       NaN       NaN     10.1   
145456         21.0       1023.5       1019.1       NaN       NaN     10.9   
145457         24.0       1021.0       1016.8       NaN       NaN     12.5   
145458         24.0       1019.4       1016.5       3.0       2.0     15.1   
145459         36.0       1020.2       1017.9       8.0       8.0     15.0   

        Temp3pm  RainToday  RainTomorrow  
0          21.8          0             0  
1          24.3          0             0  
2          23.2          0             0  
3          26.5          0             0  
4          29.7          0             0  
...         ...        ...           ...  
145455     22.4          0             0  
145456     24.5          0             0  
145457     26.1          0             0  
145458     26.0          0             0  
145459     20.9          0             2  

[145460 rows x 23 columns]

## Extracting X and Y values from the Dataset

In [74]:
x = AUS.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
y = AUS.iloc[:,-1].values

In [75]:
print(x)

[[ 2.  13.4 22.9 ... 16.9 21.8  0. ]
 [ 2.   7.4 25.1 ... 17.2 24.3  0. ]
 [ 2.  12.9 25.7 ... 21.  23.2  0. ]
 ...
 [41.   5.4 26.9 ... 12.5 26.1  0. ]
 [41.   7.8 27.  ... 15.1 26.   0. ]
 [41.  14.9  nan ... 15.  20.9  0. ]]


In [57]:
print(y)

[0 0 0 ... 0 0 2]


In [58]:
y = y.reshape(-1,1)
print(y)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [2]]


## Cleaning The Dataset(Correcting Invalid Dataset)¶


In [59]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
AUS = imputer.fit_transform(AUS)
x = imputer.fit_transform(x)
y = imputer.fit_transform(y)

In [60]:
print(AUS)

[['2008-12-01' 2 13.4 ... 21.8 0 0]
 ['2008-12-02' 2 7.4 ... 24.3 0 0]
 ['2008-12-03' 2 12.9 ... 23.2 0 0]
 ...
 ['2017-06-23' 41 5.4 ... 26.1 0 0]
 ['2017-06-24' 41 7.8 ... 26.0 0 0]
 ['2017-06-25' 41 14.9 ... 20.9 0 2]]


In [61]:
print(x)

[[ 2.  13.4 22.9 ... 16.9 21.8  0. ]
 [ 2.   7.4 25.1 ... 17.2 24.3  0. ]
 [ 2.  12.9 25.7 ... 21.  23.2  0. ]
 ...
 [41.   5.4 26.9 ... 12.5 26.1  0. ]
 [41.   7.8 27.  ... 15.1 26.   0. ]
 [41.  14.9 20.  ... 15.  20.9  0. ]]


In [62]:
print(y)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [2]]


## Spliting the data set into train and test

In [40]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=.20, random_state=0)


In [41]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(116368, 19)
(29092, 19)
(116368, 1)
(29092, 1)


## Model Traning

In [42]:
from sklearn import tree

In [43]:
model=tree.DecisionTreeClassifier()

In [44]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

## Predicting the score

In [45]:
print(model.score(x,y)*100, 'accuracy')

95.36917365598791 accuracy


## Generating Confusion Matrix

In [46]:
y_pred=model.predict(x_test)


In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[18741  3057   284]
 [ 2894  3345   127]
 [  215   150   279]]


## Predicting our model¶

In [79]:
model.predict([[2,13.4,22.9,0.6,44,1,2,20,24,71,22,1007.7,1007.1,8,8,16.9,21.8,1,1]])

array([0])